### ISSUE TITLE
Todo: Remote setup + Automatically push / pull repo remotes and update app state from project repository

### ISSUE THREAD

**Issue by madhenry** [disolution/disolution-app#1]
- [ ] Push / pull functionality
- [ ] Remote setup
- [ ] Auto push / pull user configuration in Settings
- [ ] Auto-update app projects state when repository changes by its own
- [ ] Integrate with Github to create remote repositories etc
